### ISSUE TITLE
No way to access data from an `ObjectProxy`

### ISSUE THREAD

**Issue by wagenet** [typed-ember/glint#104]
This likely means that `get` isn't being used as it should be.

```
app/components/nav/menu/app-switcher.hbs:181:54 - error TS2339: Property 'repoUrl' does not exist on type 'AsyncBelongsTo<App>'.

181                 <ExternalLink href={{this.currentApp.repoUrl}} class="menu-kebab-link">View On GitHub</ExternalLink>
```

```ts
export default class App extends Model {
  @attr('string')
  declare repoUrl: string | null;

  // ...
}
```

**Comment by boris-petrov** [comment]
@dfreeman - just wanted to mention that I hit a similar issue in my codebase (but decided to not report it exactly because I thought that you wouldn't want to handle that case because it is frowned-upon nowadays).

There will be lots of cases like that for legacy code-bases. But yes, if I were you, I would also spare myself from implementing that and just requiring everyone to migrate off of `ObjectProxy` and the likes that require `get`.

**Comment by wagenet** [comment]
I understand not making your own ObjectProxies, but what’s the recommendation for ones generated by ED? Just await them?

**Comment by wagenet** [comment]
Ultimately, I think some way to handle it, even if a special syntax will be helpful since migrating away from these will take some work in most code bases.

**Comment by dfreeman** [comment]
100%, especially given that Ember proxies are still a fact of life with Ember Data today. While I don't think it's probably worth the perf tradeoff to make `.` access work with Ember's proxies, I'm updating `{{get}}` to handle them correctly so that folks have an alternative that doesn't require a custom helper or computed property.
