### ISSUE TITLE
Inheritance for Ember components with a Mixin doesn't work

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/glint#147]
```typescript
import Component, { ArgsFor } from '@glint/environment-ember-loose/ember-component';

export interface IFoo {
  readonly Args: {
    readonly x: number;
  };
}

interface Foo extends ArgsFor<IFoo> {}

class Foo extends Component<IFoo> {}

class Bar extends Foo.extend() {
  public get bar(): number {
    return this.x;
  }
}
```

This shows an error on `this.x`. Removing `.extend()` resolves the issue.

**Comment by dfreeman** [comment]
In general Ember's classic class/mixin system is a monster for TypeScript, and there are lots of quirks and other issues with its behavior in the upstream types.

That said, Glint at least shouldn't be standing in the way of what _does_ work upstream. I think the issue here is that our exported `Component` value doesn't have any of the upstream class's static members, which we should fix.
