### ISSUE TITLE
Cannot set the type of `element` in Ember components

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/glint#148]
```typescript
import Component, { ArgsFor } from '@glint/environment-ember-loose/ember-component';

export interface IFoo {
  readonly Element: HTMLInputElement;
  readonly Args: {};
}

interface Foo extends ArgsFor<IFoo> {}

class Foo extends Component<IFoo> {
  public get bar(): string {
    return this.element.value;
  }
}
```

This should not err but it does - `Property 'value' does not exist on type 'Element'.`.

P.S. Also, the default type for `Element` probably should be `HTMLDivElement`?

**Comment by dfreeman** [comment]
Unfortunately classic components' `tagName` and such are something we can't really account for in Glint—developers essentially have to be on the honor system that the root element they're setting up aligns with the element they declare in their signature.

I personally tend to set `tagName` to `''` whenever I have to deal with `@ember/component` these days, in part because it means I can ignore all the other 'magic root element' APIs and treat my template the same way I would with `@glimmer/component`. That has the nice side effect of also playing nicely with Glint, but of course isn't something you can easily just refactor to across a whole codebase.

Unfortunately I'll have to mark this as `wontfix` (though it's really more `cantfix`)

**Comment by boris-petrov** [comment]
Fair enough. Thanks for the explanation!
