### ISSUE TITLE
Nested component have to have their full nested name for the registry

### ISSUE THREAD

**Issue by scottmessinger** [typed-ember/glint#158]
This might just be a readme fix, but I wanted to report it in case something isn't working as it should.

Let's say I have a component in the following tree:

```
app/components/group/members-table/cells/name-and-email
```

In the component file, I have: 

```ts
export default class GroupMembersTableCellsNameAndEmail extends Component<Signature> {}

```

I would have thought I just did this to register it in the registry:
```ts
declare module "@glint/environment-ember-loose/registry" {
  export default interface Registry {
    GroupMembersTableCellsNameAndEmail: typeof GroupMembersTableCellsNameAndEmail
  }
}
```

but it appears I have to use the full nested name to get it to correctly type check:

```diff
declare module "@glint/environment-ember-loose/registry" {
  export default interface Registry {
-    GroupMembersTableCellsNameAndEmail: typeof GroupMembersTableCellsNameAndEmail
+   "Group::MembersTable::Cells::NameAndEmail": typeof GroupMembersTableCellsNameAndEmail
  }
}

```

Is that working as designed? If so, I can submit a PR to update the Readme to clarify this.

**Comment by wagenet** [comment]
This is basically working as designed. The only way to do lookups is by the strong name. @dfreeman may have more to add, but I think this is the best we can do for now.

**Comment by dfreeman** [comment]
Yep, @wagenet is right—the exact reason we need the registry is to be able to map verbatim what you write in your template to the actual class that will be used at runtime, the same way e.g. [the `ember-data` model registry works](https://docs.ember-cli-typescript.com/ts/using-ts-effectively#ember-data-lookups). We basically need a way in the type system to do the work that the Ember resolver does at runtime when evaluating a template.

This also means if you may need to add your component to the registry twice if you also expect it to be invoked with curlies or via the `{{component}}` helper.

```ts
export default interface Registry {
  'Grouping::MyComponent': typeof MyComponent;
  'grouping/my-component': typeof MyComponent;
}
```

```hbs
<Grouping::MyComponent />
{{grouping/my-component}}
{{component 'grouping/my-component'}}
```

With [strict mode](https://github.com/emberjs/rfcs/blob/master/text/0496-handlebars-strict-mode.md) and template imports, the day is coming when we won't need this anymore, because any components/helpers/modifiers you use will already be statically in scope, but for now this is about the best we can do.

If you're up for opening a PR to clarify this in the docs, that would be great 🙂
