### ISSUE TITLE
Positional arguments aren't handled well with the `exactOptionalPropertyTypes` TypeScript option

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/glint#219]
```ts
// a classic component!

export interface IFoo {
  readonly PositionalArgs: [content: string | undefined];

  readonly Args: {
    readonly content: string | undefined;
  };
}
```

Using it:

```ts
...
  public content?: string;
...
```

```hbs
{{foo-component this.content}}
{{foo-component content=this.content}}
```

Leads to `Property 'content' is missing in type` for the first line and `error TS2554: Expected 2 arguments, but got 1.` for the second line. Be sure to use the `exactOptionalPropertyTypes` TypeScript option.

**Comment by dfreeman** [comment]
The way you have that signature defined, you're requiring that consumers pass both the positional _and_ the named argument, independent of `exactOptionalPropertyTypes`.

I would probably write that signature as:
```ts
export interface IFoo {
  readonly PositionalArgs: [content?: string | undefined];

  readonly Args: {
    readonly content?: string | undefined;
  };
}
```

That will allow consumers to use either the positional or named argument, but note that it won't _require_ that they use at least one. As we've discussed in other channels, positional args for classic components aren't something we're ever likely to support more completely than we do now because of the inherent complexity involved (this is a great example of that!) and the fact that that whole API is meant to be phasing out of the framework.

**Comment by boris-petrov** [comment]
Thanks for the support!
