### ISSUE TITLE
Cannot modify a helper's return signature with the `exactOptionalPropertyTypes` TypeScript option

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/glint#220]
```ts
type OptionalReturn<T extends HelperSignature> = Omit<T, 'Return'> & { readonly Return: T['Return'] | undefined };

export default abstract class BaseFooHelper<T extends HelperSignature> extends Helper<OptionalReturn<T>> {
```

This works fine with the `exactOptionalPropertyTypes` option set to `false`. When it is change to `true`:

```
Type 'OptionalReturn<T>' does not satisfy the constraint 'HelperSignature'.
  Types of property 'NamedArgs' are incompatible.
    Type 'T["NamedArgs"]' is not assignable to type 'object'.
      Type 'object | undefined' is not assignable to type 'object'.
        Type 'undefined' is not assignable to type 'object'.ts(2344)
```

I'm not sure how to fix that. I *guess* [Glint's HelpersSignature definition](https://github.com/typed-ember/glint/blob/0.6.1/packages/environment-ember-loose/ember-component/helper.ts#L21) should be changed to have `| undefined` for the three properties?

**Comment by dfreeman** [comment]
I don't think it's ideal to add `| undefined` to the signature type, because `Args: undefined` is kind of a nonsensical thing to write. If the user sets `Args` at all, it should be an object, and the point of `exactOptionalPropertyTypes` is specifically to enforce that kind of thing in a codebase: "this key isn't required, but if it's set it should be a `T`".

You might try asking in the TypeScript Discord about this; it's pretty reproducible in isolation without any Glint specifics, and it specifically seems to show up when you run a constrained type parameter through a mapped type:

https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true#code/C4TwDgpgBAsiAq5oF4oG8oEMD8AuKAzsAE4CWAdgOYDcUARnlOQK4C2dExUAvtQFChIUAEoQAjs1LEIBOIkgAeeFAgAPYBHIATArARIAfFFTNyAa3IB7AO7l+fAPQOoAVQLQABnKQeoWqRAAxsAANiD4gKDkAkhQAILGIuKS0rL6it6QBvZOUABylgC0lmBQHgDyrKTAvv7SwWFQluSlGRAekdFCAEIJohIBqfIQChVVCq0ANEwQAG6cBll8js5unspqGtq6re1QUYLQAMJKKuqaOnpDRqh9yTKtSovLeYXFpaPVjc0e62dblz58IBeDcApTudaAAEROG3O2zSEGuiX6KQeHyUU3Is3mTyAA

**Comment by boris-petrov** [comment]
I believe you misunderstood me. Or at least I don't understand your example. See this:

https://www.typescriptlang.org/play?exactOptionalPropertyTypes=false#code/JYOwLgpgTgZghgYwgAgBIQDYAdoGVgDmIcYArlCgN4BQyyAcnALYQAmAglAQM4D8AXMgD2AIwBWEBGADctZAAUh3YGGBDiGTjwHJOUOAE8APKRABrEEIDuIAHyy6AJQhkoIHaYvWQsgL7VqBAw4bm40TBwoIwAVZAgAD0gQVjD0bDxCYlcIW2Qaf2owAxxkAHksVXU4DGdXEBi4xIhk1IiMohJyHOQAXjKmFRiAGmQAclryEFHcgDI85Ao4VnUMA2QJt0FogG1xl0nRgF1kAB9kU1YIGFA2ZF9ZagSsISgwZEv4Ugw3uBFuMH0UmQQRCYQAQiEIAAxIRCNKRBoJJIpcLpKD4DrZXJI5oo+HQIzlSoaDb1aK2XL5IA

It compiles fine. Enabling `exactOptionalPropertyTypes` - it stops compiling fine. I want it to compile because I need that scenario - where I want to have a base-class helper that requires a valid `HelperSignature` as a type-argument but it itself wants to modify the `Return` of that valid `HelperSignature` and just add `| undefined` to it. If you need a full-full example, I could provide one.

I was suggesting of adding `| undefined` to `NamedArgs`, `PositionalArgs` and `Return` like so:

```ts
export interface HelperSignature {
  NamedArgs?: object | undefined;
  PositionalArgs?: Array<unknown> | undefined;
  Return?: unknown | undefined;
}
```

Not to `Args` (which as you said doesn't make sense).

**Comment by dfreeman** [comment]
My argument for not including `| undefined` equally applies to `NamedArgs` and other signature keys: adding `| undefined` opts us out of the specific protection `exactOptionalPropertyTypes` is giving you the tool to request.

The goal of my example was to demonstrate that the issue you're describing is a surprising behavior in TypeScript with `exactOptionalPropertyTypes` enabled: it seems inconsistent with other things that do work, independent of the Glint-specific details of the situation. `Omit<T, never>` is essentially a no-op on an object type, and the examples in the snippet I linked to demonstrate that, except in the final one where it suddenly seems to behave differently. As in your example, that line will only fail with `exactOptionalPropertyTypes` turned on; if you disable it in the playground config, the squiggle goes away.

The trouble seems to be that `Omit<T, never>` loses the information that a key in `T` is optional but not allowed to be explicitly `undefined`. Since the signature interface is small, you could work around that by explicitly selecting keys only if they're present:

https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true#code/JYOwLgpgTgZghgYwgAgBIQDYAdoGVgDmIcYArlCgN4BQyyAcnALYQAmAglAQM4D8AXMgD2AIwBWEBGADctZAAUh3YGGBDiGTjwHJOUOAE8APKRABrEEIDuIAHyy6AJQhkoIHaYvWQsgL7VqBAw4bm40TBwoIwAVZAgAD0gQVjD0bDxCYlcIW2Qaf2owAxxkAFlDEQh5YAQzGIAaZABpXIBeZrjEiGSwswgDIRhkWN4FGrroxpbkQUpfWULilAB5LFV1OAxnVxAYzqSU8PSofCISchzkdvKDSurahuQAckYWDi5uJ9yAMjKKqvGjyeimU6w0Wk+PzyyAocFY6gwBmQ23IIEE0QA2k8UW4ngBdZAAH2QplYEBgoDYyHmAQSWCEUDAyDJ8FIGCZcBE3DA+ikyCCITCACEQhAAGJCIRpSJ7BIHVIRDJnbK5OXdQ7S6BGVZgzY43bRWy5fJAA

**Comment by boris-petrov** [comment]
OK, thanks for all the help, this is obviously not a Glint problem so I'll close the issue.
