### ISSUE TITLE
Type 'GlimmerComponent<{}>' is not assignable to type 'TemplateComponent<{}>'.

### ISSUE THREAD

**Issue by lifeart** [typed-ember/glint#222]
![image](https://user-images.githubusercontent.com/1360552/137602403-03ec303d-10c5-4cff-b92a-b672533cabef.png)

```
Type 'GlimmerComponent<{}>' is not assignable to type 'TemplateComponent<{}>'.
  Type 'GlimmerComponent<{}>' provides no match for the signature 'new (): { [Invoke]: (args: EmptyObject) => AcceptsBlocks<EmptyObject, null>; [Context]: TemplateContext<null, EmptyObject, EmptyObject, null>; }
```

reproduction:

```
    "@glint/core": "^0.6.1",
    "@glint/environment-glimmerx": "^0.6.1",
```

```ts
import { hbs } from '@glimmerx/component';
import Component from '@glint/environment-glimmerx/component';
import type { TemplateComponent } from '@glint/environment-glimmerx/component';


const Heading: TemplateComponent<{Args: { bundlerName: string }}> = hbs`<h1>Hello {{@bundlerName}}!</h1>`;
export default class App extends Component<{}> {
  static template = hbs`
      <Heading @bundlerName="foo" />
  `;
}
```

**Comment by lifeart** [comment]
looks like it's typings error from builtin vscode TS server

**Comment by dfreeman** [comment]
In `environment-ember-loose` we ensure that we augment the base signatures for things like the `hbs` tag so that these compatibility issues with regular `tsserver` don't arise, but it looks like we haven't done that for GlimmerX. 

Ultimately vanilla TS is always going to be likely to give spurious diagnostics since, for example, it will see the `const Heading` declaration in that example as unused, but we do try to make sure to prevent avoidable errors like this with vanilla `tsserver` where possible, and we should fix this for `environment-glimmerx` in a similar way to how we have for `environment-ember-loose`.

**Comment by lifeart** [comment]
vscode setting: 
` "editor.showUnused": false`
and tsconfig:
`noUnusedLocals: false`

solve Unsed errors warning, and `@glimmerx/eslint` plugin produce correct warnings about unused things
