### ISSUE TITLE
Suppressing an error on one line causes another error to not appear

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/glint#236]
Component `foo-bar.ts`:

```ts
import Component from '@glint/environment-ember-loose/glimmer-component';

interface IFooBar {
  readonly Args: {
    readonly a: number;
    readonly b: number;
  };
}

export default class FooBar extends Component<IFooBar> {}

declare module '@glint/environment-ember-loose/registry' {
  export default interface Registry {
    FooBar: typeof FooBar;
  }
}
```

Using it:

```hbs
<FooBar
  {{! @glint-expect-error - some long comment so the line is not joined by Prettier }}
  @a={{"asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd"}}
/>
```

This shows no errors while it should - property `b` is missing. Pretty horrible, I shipped a bug because of that! :smile:

**Comment by dfreeman** [comment]
This is out of our control, because it's how TypeScript itself works!

```ts
declare function foo(arg: { stringA: string; stringB: string });

// When `stringB` is missing but `stringA` is correct, we get a
// diagnostic for the whole thing saying `stringB` is missing.
foo({ stringA: '123' });

// When `stringA` has the wrong type, though, we only get a
// diagnostic on that key, not the whole object.
foo({ stringA: 123 });

// Even if we specifically squash the `stringA` error, we still
// don't get one for the whole object despite the fact that
// `stringB` is still missing.
foo({
  // @ts-expect-error
  stringA: 123
});
```

https://tsplay.dev/NlxbXN

Gotchas like this are why I strongly encourage teams I work with to avoid `@ts-expect-error` in production code, because even in the best cases it's a blunt instrument. And to be clear, the layer Glint puts on top of TS isn't a "best case"—even if the TS team were to fix this specific scenario, there's no guarantee we'd be able to make it work in Glint since our error handling is separate from the underlying one 🙂

**Comment by boris-petrov** [comment]
Oof that's pretty bad! But thanks for the explanation! And I spent so much time debugging this... :smile:
