### ISSUE TITLE
Type Error with class-based Ember helper

### ISSUE THREAD

**Issue by NullVoxPopuli** [typed-ember/glint#342]
![image](https://user-images.githubusercontent.com/199018/170916029-18310b67-2db2-428f-81d9-de63d9ea1c46.png)

Text: `Expected 1 arguments, but got 2.`

this is weird, because I'm only passing one argument :sweat_smile: 

Code for the helper:
```js
import { getOwner } from '@ember/application';
import Helper from '@ember/component/helper';

export default class GetService extends Helper {
  compute([name]: [string]) {
    return (getOwner(this) as any).lookup(`service:${name}`);
  }
}
```

**Comment by dfreeman** [comment]
You need to specify a signature for your helper (see https://typed-ember.gitbook.io/glint/using-glint/ember/helper-and-modifier-signatures)

The bug here is ultimately another item for the list in #28 of error messages that we need to provide more context for: in this case, named args are always the first positional argument in our internal representation of the template, so TS is seeing the equivalent of `service({}, 'helper')` but since you have no signature, it's not expecting any positional arguments.

**Comment by dfreeman** [comment]
Also, I know I've said this before, but I'm going to keep saying it: please refrain from posting images of code as a bug report. I appreciate that you also included the text of the error message so that it's searchable, but the image is still going to be a black hole without context for someone working through the issue tracker with e.g. a visual impairment 🙂

**Comment by NullVoxPopuli** [comment]
Excellent! thanks!
I updated my helper to this, and everything is working great:
```ts
import { getOwner } from '@ember/application';
import Helper from '@ember/component/helper';

import type { Registry } from '@ember/service';

interface Signature<Key extends keyof Registry> {
  Args: {
    Positional: [Key];
  };
  Return: Registry[Key];
}

export default class GetService<Key extends keyof Registry> extends Helper<Signature<Key>> {
  compute([name]: [string]) {
    return (getOwner(this) as any).lookup(`service:${name}`);
  }
}
```
