### ISSUE TITLE
Look for packages at the same level as the tsconfig/jsconfig instead of in monorepo root

### ISSUE THREAD

**Issue by wagenet** [typed-ember/glint#379]

**Comment by dfreeman** [comment]
Specifically, we're trying to import from `typescript` directly in https://github.com/typed-ember/glint/blob/main/packages/core/src/language-server/util/protocol.ts#L1 rather than using the project-local version as we do everywhere else.

**Comment by wagenet** [comment]
The same thing happens with the @glint packages.

**Comment by dfreeman** [comment]
If you're specifically talking about `@glint/core`, that's expected and documented in [the release notes](https://github.com/typed-ember/glint/releases/tag/0.9.1) and [the docs site](https://typed-ember.gitbook.io/glint/using-glint/known-limitations).

Someday as Glint stabilizes we might consider bundling a copy of `@glint/core` with the Code extension under the assumption that it will be more-or-less compatible with whatever version a project is actually using, but for now we need it to be unambiguously available at startup.

TypeScript itself also works this way: if you have a copy available at the root of your workspace, Code will give you the option to use it, but if it's nested somewhere deeper you'll only be able to use the bundled copy instead (which, despite TS itself being fairly stable at this point, still frequently causes confusion for folks when their editor ends up reporting different errors because it's using a different TS version than the one they use in CI)
