### ISSUE TITLE
reference for component helper param

### ISSUE THREAD

**Issue by patricklx** [typed-ember/glint#404]
make the param for component navigate to its definition:
e.g., 
```hbs
{{component 'my-component'}}
```

clicking on  'my-component' should navigate the MyComponent defnition in the registry

**Comment by dfreeman** [comment]
This unfortunately isn't something we can control. The `{{component}}` helper works very much like a function:

```ts
function component<Name extends keyof Registry>(name: Name): Registry[Name];
```

In TypeScript, if I have an invocation`component('my-component')`, I can't click through the `my-component` string to see the corresponding entry in the registry—TypeScript's definition resolution doesn't make that connection. Since all of Glint's semantic understanding of templates is built on top of TypeScript's, we can't special-case this behavior.

Fortunately, as the framework moves toward [first-class component templates](https://rfcs.emberjs.com/id/0779-first-class-component-templates/) and away from string resolution, the need for this should begin to go away.
