### ISSUE TITLE
Parsing / Syntax errors in test ts file, ember-loose

### ISSUE THREAD

**Issue by patricklx** [typed-ember/glint#413]
the following results in the error `Property 'type' does not exist on type 'void'`

```

type Context = {
  type: string
}

module('Integration | Component | Button', (hooks) => {
  setupRenderingTest(hooks);

  test('should set as primary', async function(this: TestContext&Context,assert) {
    await render(hbs`<Button @type={{this.type}}></Button>`);
    await rerender()

    assert.ok(this.element.querySelector('button')?.getAttribute('class')?.includes('primary'));
  });
```

generated GLINT_DEBUG files show as:
```
await render(({} as typeof import("@glint/environment-ember-loose/-private/dsl")).templateExpression(function(𝚪
```
would be fixed by using `templateForBackingValue`
```
await render(({} as typeof import("@glint/environment-ember-loose/-private/dsl")).templateForBackingValue(this, function(𝚪
```

**Comment by chriskrycho** [comment]
Thanks for filing; can you include the full diagnostic? Thanks!

**Comment by dfreeman** [comment]
This looks like a type error rather than a parse/syntax error. The `templateExpression` call is the correct output there—`templateForBackingValue` would be for something like `<template>` in a class body.

I think what you're running into there is that you need to supply a type for `this` to your `render` call (see https://typed-ember.gitbook.io/glint/using-glint/ember/rendering-tests)

**Comment by patricklx** [comment]
confirmed that was the issue. thanks
