### ISSUE TITLE
`@glint` directives do not work when used as TS/JS comments

### ISSUE THREAD

**Issue by aberres** [typed-ember/glint#503]
We have a lot of test files with templates the way described here: https://typed-ember.gitbook.io/glint/using-glint/ember/rendering-tests

So far we do not yet have typed interfaces in place. To silence glint, I needed to add several hundred `{{! @glint-nocheck }}` throughout the test files like this.

```ts
await render<MyContext>(hbs`
    {{! @glint-nocheck }}
    <MyComponent @arg={{this.message}} />
`);
```

Adding them worked okish with some search/replace foo, but fixing the formatting will be a bunch of work.

It would be great if I could either completely disable checking templates in `ts` files or if `// @glint-nocheck` would work the same for `hbs` files.

**Comment by chriskrycho** [comment]
The context in which a `@glint` directive applies (or *ever* will apply) just *is* templates—because Glint intentionally does not participate in what TS does with a TS or JS file. That is: we don't want to insert ourselves into the TS pipeline *other* than translating templates into a TS representation. So that'll be a *hard* no to `// @glint-nocheck`. 😅 

For adding `{{! @glint-nocheck }}`, does the glint-auto-nocheck script not work for tests?

**Comment by aberres** [comment]
@chriskrycho Thanks for the extensive answer! Maybe adding more or less what you have written to https://typed-ember.gitbook.io/glint/using-glint/directives could clarify things. Perhaps it is just us, but a colleague of mine also tried to use comments in the TS files.

I just checked the  glint-auto-nocheck script. It works! When introducing glint initially, we were importing `hbs` from `htmlbars-inline-precompile` which did not trigger a check.
Indentation is broken for cases where a multiline comment does not have a line break after "hbs`" but this was already ugly before.
