### ISSUE TITLE
Consider switching this monorepo to pnpm

### ISSUE THREAD

**Issue by NullVoxPopuli** [typed-ember/glint#515]
I'm noticing a lot of peer issues that `yarn@v1` isn't catching throughout the ember ecosystem, and I think it's time the community abandons the objectively bad package manager.

`yarn@v1` can consume packages managed by other package managers just fine, but `yarn@v1` is too loosey goosey to author anything serious.

**Comment by dfreeman** [comment]
We did a spike to switch to `pnpm` in this repo, and in addition to hitting https://github.com/microsoft/TypeScript/issues/47663, it had a wildly negative impact on our typecheck/build times due to TS no longer seeing the same dependencies used across our different packages as being the same.

Ultimately we'll probably still make the switch at some point, particularly as the broader ecosystem figures out best practices for dealing with issues like the ones we hit, but it's not something we're going to track as an issue.
