### ISSUE TITLE
Type of property ''@each'' circularly references itself in mapped type UnwrapComputedPropertyGetters

### ISSUE THREAD

**Issue by simonihmig** [typed-ember/glint#639]
We are seeing these kinds of type errors:

```
Type of property ''@each'' circularly references itself in mapped type 'UnwrapComputedPropertyGetters<[Fn, Fn] & [unknown, unknown]>'
```

which are thrown in the `types-ramda` package:

![image](https://github.com/typed-ember/glint/assets/1325249/ae7aed37-96cd-46b8-a522-4ae15d54c577)

where there is this [recursion of the `InputTypesOfFns` generic type](https://github.com/ramda/types/blob/develop/types/util/tools.d.ts#L408).

The interesting part here is that this started only to pop up when adding an import of `@glint/environment-ember-template-imports`. This might totally be a red herring though...

Unfortunately I was not able to provide a reproduction. The original repo is closed source, and in a minimal repo I tried to put together with Glint set up and `@types/ramda` (which depends on `types-ramda`), this was not happening. So not sure what other ingredient needs to come into play to trigger this!? 🤔  

I know this is hard to track down this way, but maybe this rings a bell, or someone has some hints how I can debug this any further?

**Comment by dfreeman** [comment]
`UnwrapComputedPropertyGetters`/`Setters` are (as far as I know) only something that exists in `@types/ember*`. Since neither those nor `@each` are defined in Glint itself, I feel fairly confident saying that the root of the issue isn't in this repo.

It's totally possible that something odd is going on in the DT types _somewhere_, though I can't recall ever running into a recursion error like that with those types, and without a reproduction I'm not sure I can offer much more than that ☹️

**Comment by simonihmig** [comment]
yeah, that makes sense. Thanks for the quick feedback! I'm going to close this for now. Should I find out something that other people might also be interested, I'll post again here...
