### ISSUE TITLE
If route is named `components` model types are not inferred 

### ISSUE THREAD

**Issue by aklkv** [typed-ember/glint#720]
If we have structure like:

```
templates/
  components/
    text.hbs
routes/
  components/
    text.ts
 ```
 
 and the content of the `route.ts`:
 
 ```
 import Route from '@ember/routing/route';

export default class ComponentsTextRoute extends Route {
  model() {
    return {
      message: 'Components Text Route',
    };
  }
}
```

we get the following glint error:

<img width="650" alt="Screenshot 2024-05-17 at 12 17 09 PM" src="https://github.com/typed-ember/glint/assets/312210/a0b3e754-bb71-4881-ab5b-2755e026b2b2">

Anything outside of `template/components` folders works just fine.
I am guessing there might be some naming clash.

I can also publish repro if needed

**Comment by NullVoxPopuli** [comment]
this is an extra troll as well, because `templates/components` was the folder used for all component hbs files pre-Octane.

It'd be good to drop support for that pattern entirely in Glint so that this bug can be fixed.

**Comment by ef4** [comment]
I would be surprised if glint is the only thing that breaks when using a route named "components".

We're planning to drop support for components putting their template files into `templates/components/*.hbs` at ember 6.0, but before that point components very much might resolve template files there. In your example, if you happen to have a component named "text", ember will probably try to resolve your `templates/components/text.hbs` as its template.

It would be good to do a review across the whole stack to see what still treats `templates/components` as special, since those are all places that can get cleaned up at ember 6.0.
