### ISSUE TITLE
[Feature request] Ignore lines in HBS with `{{! glint-ignore }}` or something

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/glint#82]
Ability to ignore lines in HBS would be great.

**Comment by dfreeman** [comment]
We've punted on this so far because figuring out the right mapping is a bit thorny. Since `// @ts-ignore` operates on a line-by-line basis, and HBS lines don't necessarily map 1:1 to the emitted TS, we need to be a little bit thoughtful about what we emit in this scenario to avoid either making it impossible to ignore certain things _or_ accidentally squashing too much instead.

That's not to say having a `@ts-ignore` (and/or maybe preferably `@ts-expect-error`) equivalent isn't valuable, though—it's definitely on the radar!
