### ISSUE TITLE
A keyword-only helper does not type-check

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/glint#86]
[This commit](https://github.com/boris-petrov/glint-issues/commit/455c94d87c131943e69e788d070e4190becbd874) in the reprouction repo.

As you see, the helper has one positional parameter (that is not mandatory) and any number of named parameters. But `glint` complains:

```
app/components/test-component.hbs:1:17 - error TS2322: Type 'string' is not assignable to type 'never'.

1 {{test-helper-1 foo="bar"}}
                  ~~~
```

**Comment by dfreeman** [comment]
Unfortunately this is a limitation in how TypeScript's inference works ([playground](https://www.typescriptlang.org/play?ts=4.2.3#code/C4TwDgpgBAcghgWwgEygXigbygCwgG3wHsAuKAZ2ACcBLAOwHMoBfAbgFgAoUSKABSLkawGkTpx85dFADalWowC6UAD6zFHTl2QQAxvjhVoAMwCudXSLFQEIAGLnLougApxSZGXgeANFAB0gWCCws4SZAJCVuKSAJRkAG5ENMiaXDzQALIgfIaIUhi5VIgQwBBU5AA8GUTGNvaO0QB8rEA)):

```ts
type Named = { hello: string };
type Positionals = [string] | [];

declare function myFunction(named: Named, ...positional: Positionals): void;

type MyParams = Parameters<typeof myFunction>;
// => never
```

If you make `Positionals` either `[string]` or `[]`, you'll `MyParams` take on the expected type; the issue is just that the union doesn't play nicely.

I'd recommend writing that type as `[string?]` instead, as it more closely matches how you'd define the corresponding function and has the nice side effect of not flummoxing TypeScript 😄 

For reference, optional tuple elements were [introduced in 3.0](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#optional-elements-in-tuple-types)

**Comment by boris-petrov** [comment]
I see, thanks for pointing that out! Sorry for the false-positive!
