### ISSUE TITLE
Can't find registry module

### ISSUE THREAD

**Issue by wagenet** [typed-ember/glint#92]
```
module "@glint/environment-ember-loose/registry"
Invalid module name in augmentation, module '@glint/environment-ember-loose/registry' cannot be found.ts(2664)
```

**Comment by wagenet** [comment]
This appears to be an issue when running `tsc` directly instead of `glint`. While I realize that running `glint` directly is preferred, maybe we can still avoid breaking on this.

**Comment by chrismllr** [comment]
Is there a workaround for this in VSCode? Perhaps a way to configure VSCode to use `glint` instead of `tsc`?

**Comment by wagenet** [comment]
This issue can be resolved by adding `import '@glint/environment-ember-loose/registry';` somewhere in your `types` directory. You can also turn off VSCode's built-in TypeScript extension for the workspace as recommended in https://www.salsify.com/blog/engineering/introducing-glint-a-typed-template-solution-for-glimmerx-and-ember. I'd still like to see a better solution for this though.

**Comment by boris-petrov** [comment]
@wagenet - why do you think there will be a "better" solution? There never will be. Gslint will always be built on top of `tsc` and in order for VSCode to typecheck everything correctly, it *will* have to use Gslint instead of `tsc`.

**Comment by wagenet** [comment]
@boris-petrov fair enough. So far, `tsc` continues to pass on my project just checking fewer things than Glint. I realize this may change in the future, but right now the only thing stopping `tsc` from working is this import.

**Comment by dfreeman** [comment]
With template strict mode the need for a registry goes away, but in the meantime this is intentional behavior in `tsc` that we can't do anything about.

The fundamental issue here is that when `tsc` sees a `declare module` statement in a `.ts` file (_not_ a `.d.ts` one), it won't allow that to be the "primary" definition for that module. It assumes (generally correctly) that you're trying to augment an existing module, and this error is to protect you from typoing the name of a module that _does_ exist somewhere and then having your augmentation silently fail.

However, in order for `tsc` to realize that this module does actually exist in the real world, it needs to have an import somewhere (anywhere!) in your code that triggers it to go looking. When Glint transforms a template, it ends up triggering an import of registry module, which is why you only see that error with `tsc`/`tsserver`.

For anyone skimming through here looking for the quick answer, @wagenet's is what I'd recommend: **add `import '@glint/environment-ember-loose/registry'` somewhere in your `types` directory** (the test app in this repo does it [in its `index.d.ts`](https://github.com/typed-ember/glint/blob/5d37b896a6b52e3faf2ca6eb8ba69586efa48bf0/test-packages/ts-ember-app/types/demo-ember-app/index.d.ts#L2)) so that TypeScript won't mistakenly think it's saving you from yourself 🙂

**Comment by wagenet** [comment]
Ah, that makes sense. Thanks for the explanation.
